name: Deploy Hypertec Renewals Portal

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    name: Build and Deploy Frontend
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm ci
      
      - name: Build Frontend
        run: |
          cd frontend
          npm run build
      
      - name: Clean Build Output
        run: |
          cd frontend
          # List all files before cleanup
          echo "Files before cleanup:"
          find dist -type f | wc -l
          find dist -type f | head -20
          
          # Remove source maps and other unnecessary files
          find dist -name "*.map" -delete
          find dist -name "*.d.ts" -delete
          find dist -name "*.ts" -delete
          find dist -name "*.tsx" -delete
          find dist -name "*.jsx" -delete
          find dist -name "*.scss" -delete
          find dist -name "*.sass" -delete
          find dist -name "*.less" -delete
          find dist -name "*.css.map" -delete
          
          # Remove any node_modules that might have been copied
          rm -rf dist/node_modules
          rm -rf dist/src
          rm -rf dist/public
          
          # Remove any hidden files
          find dist -name ".*" -delete
          
          # List all files after cleanup
          echo "Files after cleanup:"
          find dist -type f | wc -l
          find dist -type f
      
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/frontend"
          output_location: "dist"
          skip_app_build: true

  build-and-deploy-api:
    runs-on: ubuntu-latest
    name: Build and Deploy API
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: api/package-lock.json
      
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
      
      - name: Verify Azure Login
        run: |
          az account show
      
      - name: Install Azure Functions Core Tools
        run: |
          npm install -g azure-functions-core-tools@4 --unsafe-perm true
      
      - name: Install API Dependencies
        run: |
          cd api
          npm ci
      
      - name: Deploy to Azure Functions
        run: |
          cd api
          func azure functionapp publish hypertec-renewals-dev-api --node
