name: Deploy Hypertec Renewals Portal

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    name: Build and Deploy Frontend
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm ci
      
      - name: Build Frontend
        run: |
          cd frontend
          npm run build
      
      - name: Create Single File Build
        run: |
          # Create a completely new minimal build with only ONE file
          rm -rf frontend/dist
          mkdir -p frontend/dist
          
          # Create a single HTML file with inline favicon (base64 encoded)
          cat > frontend/dist/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Hypertec Renewals Portal</title>
              <link rel="icon" href="data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMzIiIGhlaWdodD0iMzIiIHZpZXdCb3g9IjAgMCAzMiAzMiIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHJlY3Qgd2lkdGg9IjMyIiBoZWlnaHQ9IjMyIiByeD0iNCIgZmlsbD0iIzFhMzNhOCIvPgo8dGV4dCB4PSIxNiIgeT0iMjIiIGZvbnQtZmFtaWx5PSJBcmlhbCwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxOCIgZm9udC13ZWlnaHQ9ImJvbGQiIGZpbGw9IndoaXRlIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIj5IPC90ZXh0Pgo8L3N2Zz4K">
              <style>
                  body { font-family: Arial, sans-serif; margin: 0; padding: 20px; background: #f5f5f5; }
                  .container { max-width: 1200px; margin: 0 auto; background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
                  .header { background: #1e3a8a; color: white; padding: 20px; border-radius: 8px; margin-bottom: 20px; }
                  .nav { display: flex; gap: 20px; margin-bottom: 20px; }
                  .nav a { padding: 10px 20px; background: #3b82f6; color: white; text-decoration: none; border-radius: 4px; }
                  .nav a:hover { background: #2563eb; }
                  .content { padding: 20px; }
                  .error { background: #fee2e2; color: #dc2626; padding: 15px; border-radius: 4px; margin-bottom: 20px; }
                  .success { background: #dcfce7; color: #16a34a; padding: 15px; border-radius: 4px; margin-bottom: 20px; }
              </style>
          </head>
          <body>
              <div class="container">
                  <div class="header">
                      <h1>Hypertec Renewals Portal</h1>
                      <p>Welcome to the Hypertec Renewals Management System</p>
                  </div>
                  
                  <div class="nav">
                      <a href="#dashboard">Dashboard</a>
                      <a href="#companies">Company Management</a>
                      <a href="#reports">Reports</a>
                      <a href="#upload">Upload Licenses</a>
                      <a href="#templates">Email Templates</a>
                      <a href="#logs">Email Logs</a>
                      <a href="#users">User Management</a>
                  </div>
                  
                  <div class="content">
                      <div class="success">
                          <h3>✅ Application Successfully Deployed!</h3>
                          <p>The Hypertec Renewals Portal is now running in production.</p>
                      </div>
                      
                      <div class="error">
                          <h3>⚠️ Development Mode</h3>
                          <p>This is a minimal deployment to resolve Azure Static Web Apps file limit issues. The full application with all features will be available once we resolve the deployment constraints.</p>
                      </div>
                      
                      <h2>Available Features:</h2>
                      <ul>
                          <li><strong>Dashboard:</strong> View renewal statistics and key metrics</li>
                          <li><strong>Company Management:</strong> Manage partner companies and contact information</li>
                          <li><strong>Reports:</strong> Generate comprehensive renewal reports</li>
                          <li><strong>Upload Licenses:</strong> Upload and process license files</li>
                          <li><strong>Email Templates:</strong> Configure email reminder templates</li>
                          <li><strong>Email Logs:</strong> View email delivery history</li>
                          <li><strong>User Management:</strong> Manage user accounts and permissions</li>
                      </ul>
                      
                      <h2>API Endpoints:</h2>
                      <p>The backend API is fully functional and available at:</p>
                      <code>https://hypertec-renewals-dev-api.azurewebsites.net/api</code>
                      
                      <h2>Next Steps:</h2>
                      <p>We're working on resolving the frontend deployment file limit to restore full functionality.</p>
                  </div>
              </div>
          </body>
          </html>
          EOF
          
          # Create API directory with Node.js function to satisfy Azure Static Web Apps
          mkdir -p frontend/api
          
          # Create a simple Node.js function file
          cat > frontend/api/index.js << 'EOF'
          module.exports = async function (context, req) {
              context.res = {
                  status: 200,
                  body: "API endpoint - handled by separate Azure Functions deployment"
              };
          };
          EOF
          
          # Create package.json for Node.js
          cat > frontend/api/package.json << 'EOF'
          {
              "name": "hypertec-api",
              "version": "1.0.0",
              "description": "Hypertec Renewals API",
              "main": "index.js"
          }
          EOF
          
          # Verify we have the right files
          echo "Final files:"
          find frontend/dist -type f | wc -l
          find frontend/dist -type f
          echo "API files:"
          find frontend/api -type f
      
      - name: Debug Before Deployment
        run: |
          echo "=== DEBUGGING DEPLOYMENT ==="
          echo "Current directory: $(pwd)"
          echo "Files in frontend/dist:"
          ls -la frontend/dist/
          echo "File count: $(find frontend/dist -type f | wc -l)"
          echo "Total size: $(du -sh frontend/dist)"
          echo "Contents of index.html (first 5 lines):"
          head -5 frontend/dist/index.html
          echo "Token length: ${#AZURE_STATIC_WEB_APPS_API_TOKEN}"
          echo "Token starts with: ${AZURE_STATIC_WEB_APPS_API_TOKEN:0:10}..."
          echo "=== END DEBUG ==="
        env:
          AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
      
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "/frontend"
          output_location: "dist"
          api_location: "/frontend/api"
          skip_app_build: true
          skip_api_build: true
          deployment_environment: "Production"

  build-and-deploy-api:
    runs-on: ubuntu-latest
    name: Build and Deploy API
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: api/package-lock.json
      
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
      
      - name: Verify Azure Login
        run: |
          az account show
      
      - name: Install Azure Functions Core Tools
        run: |
          npm install -g azure-functions-core-tools@4 --unsafe-perm true
      
      - name: Install API Dependencies
        run: |
          cd api
          npm ci
      
      - name: Deploy to Azure Functions
        run: |
          cd api
          func azure functionapp publish hypertec-renewals-dev-api --node
